### ISSUE TITLE
Couldnt open one of the logfiles!

### ISSUE THREAD

**Issue by Chen-Xieyuanli** [jstraub/ptamRosBinaryFeatureRelocalization#2]
Hi, @jstraub ,

I followed the steps in README, but it didn't work out.

I'v installed the 3rd-party and compiled the ptam ros wrapper/ library and PTAM

I changed PTAM-GPL-ROS listened to ros topic 'usb_cam/image_raw'

Here comes the result:

Welcome to PTAM 

---

  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 

  Parsing settings.cfg ....

---

  first argument: number of frames to skip until next one is handed to PTAM
  second argument: number of frames to between forced relocalization
  third argument: last frame that will be fed into PTAM

---

  Skipping 0 frames before one is used.
  Forcing relocalization every 0 frames using relocalization-mechanism 0
    and I am waiting 0ms after relocalisation has been completed, before tracking is resumed
  Last Frame: 9999
CV_SSE2 defined
ros_init called
subscribeToCam called
end testing
Couldnt open one of the logfiles!

Thanks a lot for the help,

**Comment by jstraub** [comment]
Have you looked at the code  where it prints 

> Couldnt open one of the logfiles!

It probably just does not have a full path to a valid folder on your system.

**Comment by jstraub** [comment]
Did you provide the script with a rosbag to run PTAM on? 

See line 16 in
https://github.com/jstraub/ptamRosBinaryFeatureRelocalization/blob/master/launchROS_PTAM.sh

So you should run the script as `./launchROS_PTAM.sh -b path/to/rosbag`

**Comment by Chen-Xieyuanli** [comment]
*_I am sorry to reply you so late. I took part in the China Robot Contest last month and I still did not figure out this problem *_

1.
**I followed every steps in your diploma thesis  and have set the folder path as below**
**nubot@nubot-ThinkPad-T440p:~/PTAM_J.Straub$ ls**
3rdparty  ptamBriefRelocalizeStandalone  rosbags  

**nubot@nubot-ThinkPad-T440p:~/PTAM_J.Straub/ptamBriefRelocalizeStandalone$ ls**
briefRelocalize
calibrateROS_PTAM.sh
collectResults.sh
CompilationNotes.txt
do_eval.sh
imageDecompressionNode.sh
imu_and_cam.launch
launchROS_PTAM.sh
LICENSE
lshKBM
PTAM-GPL
README.md
subset_Start0_Skip0_FEAT_Reloc0_Type0_RelocWait0_NFrames9999_Processed_20160928_154143
test

**Is there anything wrong?**

2.
**Actually, I have already provided the script with a rosbag to run PTAM on, but I changed the PTAM-GPL-ROS listening topic from 'camera/image_raw' to 'usb_cam/image_raw'**

nubot@nubot-ThinkPad-T440p:~/PTAM_J.Straub/ptamBriefRelocalizeStandalone$ ./launchROS_PTAM.sh -b subset

---

 Launch programs necessary to process data with PTAM

---

Specified rosbag subset.bag
  -> Found ../rosbags/subset.bag
no starting time in cache for rosbag! -> using 0s

---

Signature: subset_Start0_Skip0_FEAT_Reloc0_Type0_RelocWait0_NFrames9999_Processed_20161101_151738
Start at 0s
Skip 0 frames before one is handed over to PTAM
Relocalize using type 0 always after 0 frames
Feature Type:  (0=BRIEF, 1=ORB, 2=FREAK)
Finish after 9999 frames

---

roscore not running -> starting a new roscore
... logging to /home/nubot/.ros/log/455d6670-a003-11e6-bac3-5cc5d4b62664/roslaunch-nubot-ThinkPad-T440p-21619.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nubot-ThinkPad-T440p:38495/
ros_comm version 1.11.20

 SUMMARY
 ========

PARAMETERS
- /rosdistro: indigo
- /rosversion: 1.11.20

NODES

auto-starting new master
process[master]: started with pid [21632]
ROS_MASTER_URI=http://nubot-ThinkPad-T440p:11311/

setting /run_id to 455d6670-a003-11e6-bac3-5cc5d4b62664
process[rosout-1]: started with pid [21645]
started core service [/rosout]
konsole: no process found
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
PTAM PID: 7892 21669 21697
PTAM is running...

**Is there anything wrong?**

**Comment by Chen-Xieyuanli** [comment]
I have changed  PTAM-GPL-ROS back to listen to ros topic 'camera/image_raw', and provided the script with a rosbag to run PTAM on. It turned out the same result as below:

  Welcome to PTAM 

---

  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 

  Parsing settings.cfg ....

---

  first argument: number of frames to skip until next one is handed to PTAM
  second argument: number of frames to between forced relocalization
  third argument: last frame that will be fed into PTAM

---

  Skipping 0 frames before one is used.
  Forcing relocalization every 0 frames using relocalization-mechanism 0
    and I am waiting 0ms after relocalisation has been completed, before tracking is resumed
  Last Frame: 9999
CV_SSE2 defined
ros_init called
subscribeToCam called
end testing
Couldnt open one of the logfiles!

**Comment by Chen-Xieyuanli** [comment]
Hi @jstraub ,

I provided the script with a rosbag including rostopic 'camera/image_raw' to run PTAM on, but the imageCallback in the ros_listener.cpp didn't work. It didn't received any images. 

Looking forward to your reply.

**Comment by Chen-Xieyuanli** [comment]
Hi, @jstraub ,

Are these log-files generated automatically， or should I create them manually before initializing？ 
keyFrameIDs.txt； framePoses.txt； relocalizationFrameNr.txt； frame2Seq.txt； briefDescriptors.txt； featureStats.log.

Looking forward to your reply.

**Comment by Chen-Xieyuanli** [comment]
Hi, @jstraub,

I worked it out. I just reinstalled it and built the folder with the guidance in your thesis.
I think you are right and it may be just something wrong with the path.

Thanks a lot for your reply!

Cheers.

**Comment by jstraub** [comment]
Great =) glad it is working now! Please feel free to reply with your solution for the path issue to make it easier for other people.
